services:
  antiloop-test-app:
    build: .
    environment:
      SITE_URL: https://localhost
    networks:
      - test
    volumes:
      - ./app/:/antiloop/app

networks:
  test:
    driver: bridge